"""empty message

Revision ID: 81498bd4712e
Revises: 
Create Date: 2025-05-14 20:02:13.300715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '81498bd4712e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islemler', schema=None) as batch_op:
        batch_op.alter_column('aciklama',
               existing_type=mssql.NTEXT(length=1073741823),
               type_=sa.Text(collation='Turkish_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('tarih',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
        batch_op.drop_constraint('FK__islemler__hesap___3B75D760', type_='foreignkey')
        batch_op.create_foreign_key(None, 'hesaplar', ['hesap_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islemler', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__islemler__hesap___3B75D760', 'hesaplar', ['hesap_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('tarih',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
        batch_op.alter_column('aciklama',
               existing_type=sa.Text(collation='Turkish_CI_AS'),
               type_=mssql.NTEXT(length=1073741823),
               existing_nullable=True)

    # ### end Alembic commands ###
